# Prevents the original block from being overwritten by subsequent respawns.
prevent-overwrite: true
# Bypass all block respawning and block protection when in creative mode.
creative-bypass: true
# Regions listed here will have their own configuration sections in the regions folder.
regions:
  - "example_region"