# You can toggle block respawning in creative mode per player via the permission saltyblockrespawn.creativerespawn.

# Prevents the original block from being overwritten by subsequent respawns.
prevent-overwrite: true
# Prevents the mining of non respawnable blocks in a region. This is to allow disabling of WorldGuard block protection.
prevent-mining-non-respawnable: false
# Regions listed here will have their own configuration sections in the regions folder.
regions:
  - "example_region"